rproxy :
  build: .
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
  environment:
    - LETSENCRYPT_EMAIL=<your_email@domain.de>
  restart: always   
